import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import prettier from "prettier";
import { Model } from "../src/model/Model";

const file = fileURLToPath(new URL("../src/model/IJsonModel.ts", import.meta.url));
const src = readFileSync(file, "utf8");

const marker = "// below this line is autogenerated";
const markerIndex = src.indexOf(marker);
if (markerIndex === -1) {
    throw new Error(`Could not find the autogenerated marker comment in ${file}`);
}
const bannerEnd = src.indexOf("\n", markerIndex);
const secondBannerEnd = src.indexOf("\n", bannerEnd + 1);
const header = src.slice(0, secondBannerEnd + 1);

const generated = header + Model.toTypescriptInterfaces() + "\n";
const formatted = await prettier.format(generated, {
    parser: "typescript",
    printWidth: 200,
    tabWidth: 4,
    useTabs: false,
});

if (process.argv.includes("--check")) {
    if (formatted !== src) {
        console.error(
            "src/model/IJsonModel.ts is out of sync with the attribute definitions.\nRun `npm run generate:interfaces` to regenerate it."
        );
        process.exit(1);
    }
    console.log("src/model/IJsonModel.ts is up to date.");
} else {
    writeFileSync(file, formatted);
    console.log("Regenerated src/model/IJsonModel.ts");
}
